regions:
  # - us-east-1
  # - us-east-2
  # - us-west-2
  # - eu-west-1
  - eu-west-2
  # - eu-west-3
  # - eu-central-1
  # - ap-south-1
  # - ap-northeast-1
  # - ap-southeast-1
  # - ap-southeast-2
images:
  # - id: ubuntu22-full-x64
  #   volume_size: 30
  #   source_ami_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*
  #   source_ami_owner: 099720109477
  # - id: ubuntu22-full-arm64
  #   volume_size: 30
  #   source_ami_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-arm64-server-*
  #   source_ami_owner: 099720109477
  - id: ubuntu24-full-x64
    volume_size: 30
    source_ami_name: ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-*
    source_ami_owner: 099720109477
  # - id: ubuntu24-full-arm64
  #   volume_size: 30
  #   source_ami_name: ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-arm64-server-*
  #   source_ami_owner: 099720109477
  # - id: windows22-full-x64
  #   volume_size: 30
  #   source_ami_name: Windows_Server-2022-English-Full-Base-*
  #   source_ami_owner: 801119661308