regions:
  - us-east-1
  - us-east-2
  - us-west-2
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - eu-central-1
  - ap-south-1
  - ap-northeast-1
  - ap-southeast-1
  - ap-southeast-2
images:
  # Ubuntu22
  - id: ubuntu22-full-x64
    volume_size: 30
    source_ami_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*
    source_ami_owner: 099720109477
    description: RunsOn Ubuntu22 x64

  - id: ubuntu22-full-arm64
    volume_size: 30
    source_ami_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-arm64-server-*
    source_ami_owner: 099720109477
    description: RunsOn Ubuntu22 arm64

  - id: ubuntu22-gpu-x64
    volume_size: 40
    source_ami_name: runs-on-dev-ubuntu22-full-x64-*
    source_ami_owner: 135269210855
    description: RunsOn Ubuntu22 GPU optimized x64

  # Ubuntu24
  - id: ubuntu24-full-x64
    volume_size: 30
    source_ami_name: ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-*
    source_ami_owner: 099720109477
    description: RunsOn Ubuntu24 x64

  - id: ubuntu24-full-arm64
    volume_size: 30
    source_ami_name: ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-arm64-server-*
    source_ami_owner: 099720109477
    description: RunsOn Ubuntu24 arm64

  - id: ubuntu24-gpu-x64
    volume_size: 40
    source_ami_name: runs-on-dev-ubuntu24-full-x64-*
    source_ami_owner: 135269210855
    description: RunsOn Ubuntu24 GPU optimized x64

  - id: ubuntu24-stepsecurity-x64
    volume_size: 30
    source_ami_name: runs-on-dev-ubuntu24-full-x64-*
    source_ami_owner: 135269210855
    description: RunsOn Ubuntu24 + StepSecurity x64

  - id: ubuntu24-stepsecurity-arm64
    volume_size: 30
    source_ami_name: runs-on-dev-ubuntu24-full-arm64-*
    source_ami_owner: 135269210855
    description: RunsOn Ubuntu24 + StepSecurity arm64

  # Windows22
  - id: windows22-full-x64
    volume_size: 40
    source_ami_name: Windows_Server-2022-English-Full-Base-*
    source_ami_owner: 801119661308
    description: RunsOn Windows2022 x64
  
  # Windows25
  - id: windows25-full-x64
    volume_size: 80
    source_ami_name: Windows_Server-2025-English-Full-Base-*
    source_ami_owner: 801119661308
    description: RunsOn Windows2025 x64